### ISSUE TITLE
tailwindcss

### ISSUE THREAD

**Issue by mizzcode** [hendraaagil/sekawan-media-fe-test#1]
izin bertanya mas, saya baru pakai tailwind dan kenapa harus pakai postcss.config.js juga ya? knpa gak hanya tailwind.config.js aja?

**Comment by hendraaagil** [comment]
Pakai config tailwind aja juga bisa, cara compile-nya lewat tailwind CLI langsung. Panduan lengkapnya ada di: https://tailwindcss.com/docs/installation.

Kalau pakai build tools macam vite / webpack disarankan memang pakai postcss agar lebih gampang pas compile-nya, kalau mau tau lebih lanjut tentang postcss bisa baca: https://postcss.org/docs/postcss-architecture.

**Comment by mizzcode** [comment]
> Pakai config tailwind aja juga bisa, cara compile-nya lewat tailwind CLI langsung. Panduan lengkapnya ada di: https://tailwindcss.com/docs/installation.
> 
> Kalau pakai build tools macam vite / webpack disarankan memang pakai postcss agar lebih gampang pas compile-nya, kalau mau tau lebih lanjut tentang postcss bisa baca: https://postcss.org/docs/postcss-architecture.

thanks mas, mau tanya lagi knpa pakai package manager nya pnpm, tidak npm yg udh umum digunakan?

**Comment by hendraaagil** [comment]
Karena pnpm lebih hemat storage 😄
